version: "3.8"

services:
  frontend:
    build: ./front
    volumes:
      - ./front:/app
      - /app/node_modules # ← protège les node_modules du container
    container_name: uwufufu_frontend
    networks:
      - app-net
    ports:
      - "${FRONT_PORT}:3000"
    command: npm run dev
    env_file: .env
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend

  backend:
    build: ./back
    volumes:
      - ./back:/app
      - /app/node_modules # ← protège les node_modules du container
    container_name: uwufufu_backend
    networks:
      - app-net
    ports:
      - "${API_PORT}:4000"
    command: npm run dev
    env_file: .env
    # environment:
    #   - DB_HOST=${POSTGRES_HOST}
    #   - DB_USER=${POSTGRES_USER}
    #   - DB_PASSWORD=${POSTGRES_PASSWORD}
    #   - DB_NAME=${POSTGRES_DB}
    #   - DB_PORT=${POSTGRES_PORT}
    #   - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    restart: unless-stopped

  dashboard:
    build: ./dashboard
    volumes:
      - ./dashboard:/app
      - /app/node_modules # ← protège les node_modules du container
    container_name: uwufufu_dashboard
    networks:
      - app-net
    ports:
      - "${DASHBOARD_PORT}:5173"
    command: npm run dev
    env_file: .env
    environment:
      - VITE_API_URL=${VITE_API_URL}
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: uwufufu_db
    restart: unless-stopped
    environment:
      - POSTGRES_HOST: ${POSTGRES_HOST}
      - POSTGRES_PORT: ${POSTGRES_PORT}
      - POSTGRES_DB: ${POSTGRES_DB}
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-net

  nginx:
    image: nginx:stable
    container_name: uwufufu_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./back/uploads:/var/www/uwufufu/uploads
    depends_on:
      - frontend
      - backend
      - dashboard
    networks:
      - app-net
    restart: unless-stopped

volumes:
  db_data:

networks:
  app-net:
    driver: bridge
